### ISSUE TITLE
Teams must provide an IPFS CID for the frontend code which must match their generated code.

### ISSUE THREAD

**Issue by kathodler** [MutantDAO/it_tasks#22]
Ok so the best way we can ensure verifiability of frontend code is to make it so you have to deploy your build folder to ipfs and provide an ipfs CID of your code which we will point to.

**Comment by kathodler** [comment]
So for Fleek you can use this Github Action which will print out the ipfs deploy url:
 
```yaml
on: [push]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    name: A job to test the action-deploy action by deploying a test site
    steps:
      - uses: actions/checkout@v2
      - name: Deploy test site
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
```

**Comment by kathodler** [comment]
Pinata

```yaml
on: [push]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    name: A job to test the action-deploy action by deploying a test site
    steps:
      - uses: actions/checkout@v2
      - name: Deploy test site
        id: deploy
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: ${{ github.sha }}
          path: "./ui/app/dist"
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_KEY }}
          verbose: true
          remove-old: true
      - name: Get the output cid
        run: echo "Deploy CID is ${{  steps.deploy.outputs.hash }}"
```
